name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Display root directory contents
        run: ls -la
      - name: Display XPhone directory contents
        run: ls -la XPhone
      - name: Restore dependencies for XPhone.Api
        run: dotnet restore ./XPhone/XPhone.Api/XPhone.Api.csproj

      - name: Build XPhone.Api
        run: dotnet build ./XPhone/XPhone.Api/XPhone.Api.csproj --no-restore

      - name: Test
        run: dotnet test ./XPhone/XPhone.Tests/XPhone.Tests.csproj --no-build --verbosity normal