name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Display root directory contents
        run: ls -la
      - name: Display XPhone directory contents
        run: ls -la XPhone
      - name: Restore dependencies for XPhone.Api
        run: dotnet restore ./XPhone/XPhone.Api/XPhone.Api.csproj

      - name: Restore dependencies for XPhone.Application
        run: dotnet restore ./XPhone/XPhone.Application/XPhone.Application.csproj

      - name: Restore dependencies for XPhone.Domain
        run: dotnet restore ./XPhone/XPhone.Domain/XPhone.Domain.csproj

      - name: Restore dependencies for XPhone.Infrastructure
        run: dotnet restore ./XPhone/XPhone.Infrastructure/XPhone.Infra.csproj

      - name: Restore dependencies for XPhone.Tests
        run: dotnet restore ./XPhone/XPhone.Tests/XPhone.Tests.csproj
      
      - name: Build
        run: dotnet build ./XPhone --no-restore
      - name: Test
        run: dotnet test ./XPhone --no-build --verbosity normal